
export enum Basic {
	ANIMAL_CARE = 'Animal Care',
	ANIMAL_TRAINING = 'Animal Training',
	BLATHER = 'Blather',
	CHANNELLING = 'Channelling',
	CHARM = 'Charm',
	CHARM_ANIMAL = 'Charm Animal',
	COMMAND = 'Command',
	CONCEALMENT = 'Concealment',
	CONSUME_ALCOHOL = 'Consume Alcohol',
	DISGUISE = 'Disguise',
	DODGE_BLOW = 'Dodge Blow',
	DODGE_BLOWS = 'Dodge Blows',
	DRIVE = 'Drive',
	EVALUATE = 'Evaluate',
	FOLLOW_TRAIL = 'Follow Trail',
	GAMBLE = 'Gamble',
	GOSSIP = 'Gossip',
	HAGGLE = 'Haggle',
	HEAL = 'Heal',
	PUBLIC_SPEAKING = 'Public Speaking',
	HYPNOTISM = 'Hypnotism',
	INTIMIDATE = 'Intimidate',
	LIP_READING = 'Lip Reading',
	MAGICAL_SENSE = 'Magical Sense',
	NAVIGATE = 'Navigate',
	NAVIGATION = 'Navigation',
	NAVIGATOR = 'Navigator',
	OUTDOOR_SURVIVAL = 'Outdoor Survival',
	PERCEPTION = 'Perception',
	PICK_LOCK = 'Pick Lock',
	PREPARE_POISON = 'Prepare Poison',
	READ_WRITE = 'Read/Write',
	RIDE = 'Ride',
	ROW = 'Row',
	RUNECRAFT = 'Runecraft',
	SAIL = 'Sail',
	SCALE_SHEER_SURFACE = 'Scale Sheer Surface',
	SEARCH = 'Search',
	SET_TRAP = 'Set Trap',
	SHADOWING = 'Shadowing',
	SILENT_MOVE = 'Silent Move',
	SLEIGHT_OF_HAND = 'Sleight of Hand',
	SWIM = 'Swim',
	TORTURE = 'Torture'
}
export enum Performer {
	STORYTELLER = 'Storyteller',
	ACTOR = 'Actor',
	PALM_READER = 'Palm Reader',
	COMEDIAN = 'Comedian',
	DANCER = 'Dancer',
	SINGER = 'Singer',
	MUSICIAN = 'Musician',
	ANY_TWO = 'any two',
	ANY_ONE = 'any one',
	ANY = 'any'
}
export enum Trade {
	APOTHECARY = 'Apothecary',
	ARMOURER = 'Armourer',
	AVIARIST = 'Aviarist',
	HORSE_TRADER = 'Horse trader',
	KENNEL_MASTER = 'Kennel master',
	BOWYER = 'Bowyer',
	STABLEMAN = 'Stableman',
	ARTIST = 'Artist',
	CALLIGRAPHER = 'Calligrapher',
	CARPENTER = 'Carpenter',
	CARTOGRAPHER = 'Cartographer',
	COOK = 'Cook',
	HERBALIST = 'Herbalist',
	FARMER = 'Farmer',
	GUNSMITH = 'Gunsmith',
	MERCHANT = 'Merchant',
	MINER = 'Miner',
	SMITH = 'Smith',
	PROSPECTOR = 'Prospector',
	STONEWORKER = 'Stoneworker',
	ANY_ONE = 'any one',
	ANY_TWO = 'any two',
	ANY_THREE = 'any three',
	ANY = 'any',
	SHIPWRIGHT = 'Shipwright'
}
export enum SecretLanguage {

	BATTLE_TONGUE = 'Battle Tongue',
	GUILD_TONGUE = 'Guild Tongue',
	PRISON_CANT = 'Prison Cant',
	RANGER_TONGUE = 'Ranger Tongue',
	THIEVES_TONGUE = 'Thieves\' Tongue',
	ANY_ONE = 'any one',
	ANY_TWO = 'any two'
}
export enum ArcaneLanguage {
	ARCANE_DWARF = 'Arcane Dwarf',
	DAEMONIC = 'Daemonic',
	ARCANE_ELF = 'Arcane Elf',
	MAGICK = 'Magick',
	ANY_ONE = 'any one'
}
export enum CommonKnowledge {
	BORDER_PRINCES = 'Border Princes',
	TILEA = 'Tilea',
	BRETONNIA = 'Bretonnia',
	CHAOS_WASTES = 'Chaos Wastes',
	DWARFS = 'Dwarfs',
	EMPIRE = 'Empire',
	ESTALIA = 'Estalia',
	KISLEV = 'Kislev',
	NORSCA = 'Norsca',
	SKAVEN = 'Skaven',
	TROLL_COUNTRY = 'Troll Country',
	ANY_THREE = 'any three',
	ANY_TWO = 'any two',
	ANY = 'any',
	ANY_ONE = 'any one',
	THE_EMPIRE = 'the Empire',
	THE_WASTELAND = 'the Wasteland'
}
export enum Language {
	BORDER_PRINCES = 'Border Princes',
	BRETON = 'Breton',
	TILEAN = 'Tilean',
	REIKSPIEL = 'Reikspiel',
	BRETONNIA = 'Bretonnia',
	CHAOS_WASTES = 'Chaos Wastes',
	DWARFS = 'Dwarfs',
	EMPIRE = 'Empire',
	ESTALIAN = 'Estalian',
	CLASSICAL = 'Classical',
	NORSE = 'Norse',
	KISLEVITE = 'Kislevite',
	NORSCA = 'Norsca',
	SKAVEN = 'Skaven',
	QUEEKISH = 'Queekish',
	UNGOL = 'Ungol',
	STRIGANY = 'Strigany',
	TROLL_COUNTRY = 'Troll Country',
	ANY_FOUR = 'any four',
	ANY_THREE = 'any three',
	ANY_TWO = 'any two',
	ANY = 'any',
	ANY_ONE = 'any one',
	THE_EMPIRE = 'the Empire',
	THE_WASTELAND = 'the Wasteland'
}
export enum AcademicKnowledge {
	ASTRONOMY_OR_HISTORY = 'Astronomy or History',
	ASTRONOMY = 'Astronomy',
	DAEMONOLOGY = 'Daemonology',
	ENGINEERING = 'Engineering',
	GENEALOGY_HERALDRY = 'Genealogy/Heraldry',
	HISTORY = 'History',
	LAW_OR_INTIMIDATE = 'Law or Intimidate',
	LAW = 'Law',
	MAGIC = 'Magic',
	NECROMANCY = 'Necromancy',
	RELIGION = 'Religion',
	RUNES = 'Runes',
	SCIENCE = 'Science',
	SPIRITS = 'Spirits',
	STRATEGY_TACTICS = 'Strategy/Tactics',

	THEOLOGY = 'Theology',
	ANY_FOUR = 'any four',
	ANY_ONE = 'any one',
	ANY_THREE = 'any three',
	ANY_TWO = 'any two',
	GEOGRAPHY = 'geography',
	THE_ARTS = 'the Arts'
}
export enum SecretSigns {
	ASTROLOGER = 'Astrologer',
	RANGER = 'Ranger',
	SCOUT = 'Scout',
	TEMPLAR = 'Templar',
	THIEF = 'Thief',
	ANY_ONE = 'any one',
	ANY_TWO = 'any two'
}

export enum VariableSkills {
	PERFORMER = 'Performer',
	TRADE = 'Trade',
	SECRET_LANGUAGE = 'Secret Language',
	SPEAK_ARCANE_LANGUAGE = 'Speak Arcane Language',
	SPEAK_LANGUAGE = 'Speak Language',
	COMMON_KNOWLEDGE = 'Common Knowledge',
	ACADEMIC_KNOWLEDGE = 'Academic Knowledge',
	SECRET_SIGNS = 'Secret Signs'
}

export const Enums = {
	Basic,
	Performer,
	Trade,
	SecretLanguage,
	ArcaneLanguage,
	CommonKnowledge,
	Language,
	AcademicKnowledge,
	SecretSigns,
	VariableSkills
}